### PR TITLE
Upgrade to io.dropwizard 0.7.0; add support to load servlets in dropwizard environment

### PR DESCRIPTION
**Pull request by tranhuong**
This pull request includes merges from two other pull requests (still open):
- https://github.com/hmsonline/dropwizard-spring/pull/11 - load servlet configs into dropwizard environment;
- https://github.com/hmsonline/dropwizard-spring/pull/10 - upgrade to io.dropwizard 0.7.0;

Additional changes:
- upgrade dependencies and plugin to latest compatible release
- upgrade to java 7
- update README

### CODE REVIEW

**Comment by mdbouchard** [comment]
Thank you for using my pull request to handle the DropWizard 0.7.0 upgrade! Now if only this project will merge it in :-).

**Comment by tranhuong** [comment]
no problem. i work closely with the owners of this repo and am actively working to get code reviews and releases done. hopefully coming shortly.

**Comment by mdbouchard** [comment]
That's awesome! I'm looking forward to using the official build instead of my forked version we have published in our local repo.

**Comment by boneill42** [comment]
LGTM

**Pull request merged**
